#!/usr/bin/env bash

# I don't want to talk about this ever again
fname='aks-sideload-debug.yaml'
tname='aks-sideload-debug.yaml.tmpl'
sname='sideload.sh'

insert_bash_hammer=$(cat ${sname})

rm -f ${fname} temp.yml

( echo "cat <<EOF >${fname}";
  cat ${tname};
  echo "EOF";
) >temp.yml
. temp.yml
cat ${fname}
