## Cluster Operations
clusterSystem:
  name: cluster-system-extras
  enabled: false

ingress:
  enabled: false
  name: ingress

certManager:
  enabled: false
  name: cert-manager

externalDNS:
  enabled: false
  name: external-dns

## CI/CD
spinnaker:
  enabled: false
  name: spinnaker

concourse:
  enabled: false
  name: concourse

minio:
  enabled: false
  name: minio

harbor:
  enabled: false
  name: harbor

## Metrics
grafana:
  enabled: true
  repository:
    name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  name: grafana
  namespace: metrics
  chart: stable/grafana
  version: 4.4.0
  values:
    - values/grafana/values.yaml.gotmpl

prometheus:
  enabled: true
  repository:
    name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  name: prometheus
  namespace: metrics
  chart: stable/prometheus
  version: 8.11.4
  values:
    - values/prometheus/values.yaml.gotmpl

loki:
  enabled: false
  repository:
    url: https://grafana.github.io/loki/charts
    name: loki
  name: loki
  namespace: logging
  chart: loki/loki
  version: 0.24.0
  values:
    - values/loki/values.yaml.gotmpl
  raw:
    - values/loki/raw.yaml.gotmpl

promtail:
  enabled: false
  repository:
    url: https://grafana.github.io/loki/charts
    name: loki
  name: promtail
  namespace: logging
  chart: loki/promtail
  version: 0.17.0
  values:
    - values/promtail/values.yaml.gotmpl

elasticsearch:
  enabled: false
  name: elasticsearch

kibana:
  enabled: false
  name: kibana


fluentbit:
  enabled: false
  name: fluentbit


# misc
kubeapps:
  enabled: false
  name: kubeapps

# wavefront
wavefront:
  enabled: false
  name: wavefront
